/* global use, db */


use('citystaymongodb');
db.utilizatori.drop();

db.utilizatori.insertMany([
    {
        utilizatorId: "UTL001",
        prenume: "Maria",
        nume: "Pop",
        email: "mariapop@gmail.com",
        telefon: "+40745745678",
        parolaHash: "parola1!.*",
        dataNasterii: new Date("2000-12-04"),
        pozaProfil: "maria.jpg",
        dataCreare: new Date("2026-01-01"),
        roluri: ["gazda", "oaspete"]
    },
    {
        utilizatorId: "UTL002",
        prenume: "Davis",
        nume: "Benjamin",
        email: "davisbenji@gmail.com",
        telefon: "+4065456783",
        parolaHash: "davidthewinner000",
        dataNasterii: new Date("1998-05-20"),
        pozaProfil: "davidbenji.jpg",
        dataCreare: new Date("2026-01-01"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL003",
        prenume: "Monica",
        nume: "Georgescu",
        email: "monicageorgescu@gmail.com",
        telefon: "+4045678653",
        parolaHash: "parolamonica",
        dataNasterii: new Date("2005-11-09"),
        pozaProfil: "monicageorge.jpg",
        dataCreare: new Date("2016-12-03"),
        roluri: ["gazda", "oaspete"]
    },
    {
        utilizatorId: "UTL004",
        prenume: "Paul",
        nume: "Mihaila",
        email: "paulmihaila@gmail.com",
        telefon: "+40455674500",
        parolaHash: "paulpaulmihaila&*%$",
        dataNasterii: new Date("1990-12-09"),
        pozaProfil: "paulmihaila.jpg",
        dataCreare: new Date("2022-12-03"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL005",
        prenume: "Radu",
        nume: "Vulpe",
        email: "raduvulpe@gmail.com",
        telefon: "+4042678003",
        parolaHash: "parola654",
        dataNasterii: new Date("1998-04-13"),
        pozaProfil: "paulv.jpg",
        dataCreare: new Date("2010-12-03"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL006",
        prenume: "Elena",
        nume: "Ionescu",
        email: "elena_ionescu@gmail.com",
        telefon: "+4049978653",
        parolaHash: "elenamaria0.",
        dataNasterii: new Date("2005-08-18"),
        pozaProfil: "elenaaionesu.jpg",
        dataCreare: new Date("2013-04-03"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL007",
        prenume: "Eric",
        nume: "Grigore",
        email: "ericgrigore@gmail.com",
        telefon: "+40454568653",
        parolaHash: "parolasite",
        dataNasterii: new Date("1970-11-09"),
        pozaProfil: "monicageorge.jpg",
        dataCreare: new Date("2024-10-03"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL008",
        prenume: "Bianca",
        nume: "Soare",
        email: "biancasoare333@gmail.com",
        telefon: "+4045000653",
        parolaHash: "biencutaparola",
        dataNasterii: new Date("2001-11-09"),
        pozaProfil: "biancasoare.jpg",
        dataCreare: new Date("2026-01-03"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL009",
        prenume: "Costin",
        nume: "Dumitrescu",
        email: "costindumi@gmail.com",
        telefon: "+4040008653",
        parolaHash: "costin_costin.!",
        dataNasterii: new Date("2002-07-09"),
        pozaProfil: "costin.jpg",
        dataCreare: new Date("2025-12-04"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL010",
        prenume: "Irina",
        nume: "Dobre",
        email: "irinadobre04@gmail.com",
        telefon: "+4009764362",
        parolaHash: "parola12345",
        dataNasterii: new Date("2009-11-09"),
        pozaProfil: "irinadobre.jpg",
        dataCreare: new Date("2019-11-09"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL011",
        prenume: "Cristina",
        nume: "Stancu",
        email: "cristinastandcu@gmail.com",
        telefon: "+40741000007",
        parolaHash: "crisustancu11",
        dataNasterii: new Date("1994-03-15"),
        pozaProfil: "cristina.jpg",
        dataCreare: new Date("2019-11-05"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL012",
        prenume: "Bogdan",
        nume: "Marin",
        email: "bogdanmarin@gmail.com",
        telefon: "+40741000008",
        parolaHash: "parola9",
        dataNasterii: new Date("1987-06-20"),
        pozaProfil: "bogdan.jpg",
        dataCreare: new Date("2012-11-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL013",
        prenume: "Alina",
        nume: "Dinu",
        email: "alinadinu@gmail.com",
        telefon: "+40741000009",
        parolaHash: "password",
        dataNasterii: new Date("1996-09-11"),
        pozaProfil: "alina.jpg",
        dataCreare: new Date("2022-11-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL014",
        prenume: "Florin",
        nume: "Barbu",
        email: "florinbarbu@gmail.com",
        telefon: "+40741000010",
        parolaHash: "paword123",
        dataNasterii: new Date("1983-12-01"),
        pozaProfil: "florin.jpg",
        dataCreare: new Date("2010-12-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL015",
        prenume: "Ioana",
        nume: "Nistor",
        email: "ioananistor@gmail.com",
        telefon: "+40741000011",
        parolaHash: "ioana27",
        dataNasterii: new Date("1991-04-22"),
        pozaProfil: "ioana.jpg",
        dataCreare: new Date("2017-10-05"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL016",
        prenume: "Alexandru",
        nume: "Preda",
        email: "alexandrupreda@gmail.com",
        telefon: "+40741000012",
        parolaHash: "predaparola",
        dataNasterii: new Date("1989-07-14"),
        pozaProfil: "alex.jpg",
        dataCreare: new Date("2022-11-05"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL017",
        prenume: "Raluca",
        nume: "Matei",
        email: "ralucamatei@gmail.com",
        telefon: "+40741000013",
        parolaHash: "parola..0",
        dataNasterii: new Date("1997-02-28"),
        pozaProfil: "raluca.jpg",
        dataCreare: new Date("2023-03-05"),
        roluri: ["gazda", "oaspete"]
    },
    {
        utilizatorId: "UTL018",
        prenume: "Vlad",
        nume: "Ciobanu",
        email: "vladciobanu@gmail.com",
        telefon: "+40741000014",
        parolaHash: "ciobanuvlad2007",
        dataNasterii: new Date("1993-08-05"),
        pozaProfil: "vlad.jpg",
        dataCreare: new Date("2019-11-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL019",
        prenume: "Gabriela",
        nume: "Stoica",
        email: "gabrielastoica@gmail.com",
        telefon: "+40741000015",
        parolaHash: "gabistoica",
        dataNasterii: new Date("1986-11-30"),
        pozaProfil: "gabriela.jpg",
        dataCreare: new Date("2022-11-05"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL020",
        prenume: "Marius",
        nume: "Luca",
        email: "mariusluca@gmail.com",
        telefon: "+40741000016",
        parolaHash: "mariuslucca89",
        dataNasterii: new Date("1992-05-17"),
        pozaProfil: "marius.jpg",
        dataCreare: new Date("2020-01-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL021",
        prenume: "Diana",
        nume: "Oprea",
        email: "dianaoprea@gmail.com",
        telefon: "+40741000017",
        parolaHash: "opreadia487",
        dataNasterii: new Date("1995-10-09"),
        pozaProfil: "diana.jpg",
        dataCreare: new Date("2019-11-05"),
        roluri: ["gazda", "oaspete"]
    },
    {
        utilizatorId: "UTL022",
        prenume: "Catalin",
        nume: "Florea",
        email: "catalinflorea@gmail.com",
        telefon: "+40741000018",
        parolaHash: "catalinflore",
        dataNasterii: new Date("1984-01-25"),
        pozaProfil: "catalin.jpg",
        dataCreare: new Date("2025-11-05"),
        roluri: ["oaspete"]
    },
    {
        utilizatorId: "UTL023",
        prenume: "Andreea",
        nume: "Dumitru",
        email: "andreeadumitru@gmail.com",
        telefon: "+40741000019",
        parolaHash: "andreea2000",
        dataNasterii: new Date("1998-06-13"),
        pozaProfil: "andreea.jpg",
        dataCreare: new Date("2024-10-05"),
        roluri: ["gazda"]
    },
    {
        utilizatorId: "UTL024",
        prenume: "Stefan",
        nume: "Constantin",
        email: "stefanconstantin@gmail.com",
        telefon: "+40741000020",
        parolaHash: "cconstantin",
        dataNasterii: new Date("1990-03-08"),
        pozaProfil: "stefan.jpg",
        dataCreare: new Date("2019-11-10"),
        roluri: ["gazda", "oaspete"]
    },
    {
        utilizatorId: "UTL025",
        prenume: "Laura",
        nume: "Gheorghe",
        email: "lauragheorghe@gmail.com",
        telefon: "+40741000021",
        parolaHash: "parola8",
        dataNasterii: new Date("1993-07-19"),
        pozaProfil: "laura.jpg",
        dataCreare: new Date("2019-12-05"),
        roluri: ["oaspete"]
    }
]);

